# .github/workflows/main.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v2 

      - name: Set up AWS credentials for ECR
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # AWS Access Key ID
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # AWS Secret Access Key
          aws-region: us-east-1  # AWS region for ECR

      - name: Authentication - Login to AWS ECR
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URI }}  # Authenticate Docker to ECR

      - name: Building Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY_URI }}:latest .  # Build Docker image with the tag pointing to ECR

      - name: Pushing Docker image to AWS ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest  # Push the Docker image to ECR

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure this job runs after the build job

    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Authentication - Setting up AWS credentials for ECS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # AWS Access Key ID
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # AWS Secret Access Key
          aws-region: ap-south-1  # AWS region for ECS

      - name: Deploying to ECS
        run: |
          aws ecs update-service \
            --cluster vecluster \
            --service ve3service \
            --force-new-deployment \
            --region ap-south-1  # Deploying the Docker image to ECS

  test:
    runs-on: ubuntu-latest
    needs: deploy  # Ensure this job runs after the deploy job

    steps:
      - name: Run integration tests
        run: |
          curl -f http://13.201.85.142 || exit 1  # Running integration test by sending a request to your app

      - name: Rollback on failure
        if: failure()
        run: |
          aws ecs update-service \
            --cluster vecluster \
            --service ve3service \
            --force-new-deployment \
            --region ap-south-1 \
            --rollback  # Rollback to the previous task

