name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Amazon ECR Public
      - name: Log in to Amazon ECR Public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public
          aws-region: us-east-1  # Replace with your AWS region

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build --build-arg TARGETPLATFORM=linux/amd64 --tag ${{ secrets.ECR_PUBLIC_REPOSITORY }}:latest .

      # Step 5: Push Docker image to Amazon ECR Public
      - name: Push Docker image
        run: |
          docker push ${{ secrets.ECR_PUBLIC_REPOSITORY }}:latest

      # Step 6: Deploy to ECS
      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: task-definition.json
          service: ve3service
          cluster: vecluster
          wait-for-service-stability: true

      # Step 7: Run integration tests
      - name: Run integration tests
        run: |
          curl -f http://43.205.195.11/api/test || exit 1

      # Step 8: Rollback on failure
      - name: Rollback deployment
        if: failure()
        run: |
          aws ecs update-service --cluster my-ecs-cluster --service my-ecs-service --force-new-deployment
